### PR TITLE
Added ROP 1 to picoctf 2013 writeups.

### PR DESCRIPTION
**Pull request by Bretley**

### CODE REVIEW

**Comment by Bretley** [comment]
I'm super unfamiliar with Git conventions, sorry in advance. However, in my attempt to learn Git I will be adding  as many writeups as I can. Thank you for your time.

**Comment by redknight99** [comment]
Good stuff!

The admins will probably want you to update the master 2013 picoctf README file with the link to your write up.  Check out their [CONTRIBUTING.md for reference.](https://github.com/ctfs/write-ups-2013/blob/master/CONTRIBUTING.md)

**Comment by Bretley** [comment]
I've not done much github before (ever really). When I include the link to the problem in the README.md, should I make the link as it would appear in my repo or as if it were already a part of master.

**Comment by abpolym** [comment]
@bert88sta Hey good job! To answer your question: The [root README]() of a given CTF directory usually contains links to all tasks in three sections - Tasks with "repo-local" writeups (Compelted writeups), tasks with external links to other writeups only (External write-ups only) and tasks without any writeups (Missing writeups). See [here](https://github.com/ctfs/write-ups-2016/tree/master/internetwache-ctf-2016) for a comparison. You've added a "repo-local" writeup to the pico CTF, which means that you should update the [root README.md](https://github.com/ctfs/write-ups-2013/blob/master/pico-ctf-2013/README.md) of the picoCTF directory by replacing the `#` sign in the "ROP-1" markdown reference with "rop-1" (compare it with already existing directories).

**Comment by Bretley** [comment]
Ok so I fixed the link to the problem in the picoctf root folder, do i need to close this pull request and submit another?

**Comment by Bretley** [comment]
Alright, I've added the links to the problems in the picoctf README.md. Also have added ROP 2

**Comment by Bretley** [comment]
Alright, that's all of the ROP problems done :+1:

**Pull request closed without merging**
