### PR TITLE
Added all rop problems and fixed a typo

### PR DESCRIPTION
**Pull request by Bretley**
I didn't rebase them, I just took my writeups, deleted the repo and put them in a newly forked one. It's a shame to lose the commits, but I can get more as we go :+1:

### CODE REVIEW

**Comment by Bretley** [comment]
Last commits fixed the README that I screwed up

**Comment by Bretley** [comment]
@dhanvi do these all need squashed into one? :/

**Comment by Bretley** [comment]
@abpolym @dhanvi  what do i still need to do for this?

**Comment by abpolym** [comment]
@bert88sta Nothing sorry - I had to finish my thesis and had no time :) Thanks for your work!

**Comment by Bretley** [comment]
@abpolym Sweet what was it on? I almost have all the overflow problems done (Apparently they were given the hint to disable ASLR for the last one, I couldn't solve it without it.)

**Comment by abpolym** [comment]
@bert88sta Fingerprinting Mobile Malware :). Very nice work of yours, keep contributing, appreciate it!

**Pull request merged**
