### PR TITLE
All ROP problems added to Picoctf2013

### PR DESCRIPTION
**Pull request by Bretley**

### CODE REVIEW

**Comment by Bretley** [comment]
Is there anything else to be done here?

**Comment by dhanvi** [comment]
@bert88sta sorry for the delay in looking at the merge 

I work you have done looks good but you need [squash](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) the commits and resolve the [conflicts](https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/)

**Comment by dhanvi** [comment]
@bert88sta if you can help us please have a look at this https://github.com/ctfs/write-ups-2016/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22 

and join https://gitter.im/ctfs/write-ups

**Comment by Bretley** [comment]
@dhanvi I will absolutely try to help! writeups are how I learned to hack and code, and I want it to be easy for others to learn.

**Pull request closed without merging**
