### PR TITLE
Create pretty-hard-programming

### PR DESCRIPTION
**Pull request by redknight99**
Adding an entry and solution to the problem pretty hard programming.

### CODE REVIEW

**Comment by abpolym** [comment]
@redknight99 Can you add a reference in the root README.md too? :)

**Comment by redknight99** [comment]
I'm still kinda new to Git. You mean change Pretty Hard Programming from TODO to completed? @YASME-Tim

**Comment by redknight99** [comment]
There we go . I got some Git tutoring and I've updated the root file to match the other challenges. Let me know if anything needs changing or fixing.

**Comment by abpolym** [comment]
@redknight99 Yeah can you squash these commits in any way? 10 commits for a file change seems a bit much :)

**Comment by redknight99** [comment]
Sounds good sir! I'll send a new cleaner one.

**Pull request closed without merging**
