### PR TITLE
Add hacklu CTF 2013

### PR DESCRIPTION
**Pull request by nyx0**

### CODE REVIEW

**Comment by abpolym** [comment]
Wow cool, thanks @nyx0 . Just out of interest: Did you use the [ctf generation tool](https://github.com/ctfs/write-ups-tools/tree/master/genctf)?

**Comment by dhanvi** [comment]
@nyx0 that's very good work :smile: 

but you missed to categories the tasks into folders inside the ctf directory so @YASME-Tim we can fix it or revert the pull request and ask @nyx0 to create a new pull which do you suggest ??

**Comment by abpolym** [comment]
@dhanvi We can just use `git mv`, sec I'll demonstrate

**Comment by nyx0** [comment]
@YASME-Tim No unfortunately, but I'll use it for my next contributions for sure ;).
@dhanvi Sorry for the inconvenience.

**Comment by dhanvi** [comment]
@nyx0 no problem you have done a great job :smile: 

@YASME-Tim I have never used `git mv` I think we have a similar issue in many of the writeup in 2014 I guess better we create a new issue there

**Pull request merged**
